name: Publish to GitHub Package Registry

on:
  release:
    types: [ released ]

permissions:
  packages: read
  contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  publish-npm:

    name: Publish to NPM
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}

  publish-gpr:
    name: Publish to GitHub Package Registry
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@lordofdestiny"
      - run: npm ci
      - name: Set up .npmrc file
        run: echo registry=https://npm.pkg.github.com/lordofdestiny >> .npmrc
      - name: Publish to GitHub Package Registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

