name: PR Sanity

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    paths:
      - 'src/**.ts'
      - 'tsconfig*.json'
      - 'test/**.spec.ts'
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
